### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by mapsam** [mapsam/beepboop#13]
Is it logo time?

**Comment by suhasdeshpande** [comment]
https://www.wix.com/logo/ offers a pretty straightforward way to generate logos. 

e.g. 

<img width="550" alt="Screen Shot 2020-11-24 at 11 40 20 AM" src="https://user-images.githubusercontent.com/606167/100143319-03bb5b80-2e4a-11eb-8517-253481dbd6ee.png">

<img width="466" alt="Screen Shot 2020-11-24 at 11 40 54 AM" src="https://user-images.githubusercontent.com/606167/100143323-04ec8880-2e4a-11eb-9db8-f956664e53bb.png">

**Comment by mapsam** [comment]
I just used the ✏️ emoji lol
